version: '1.0'
project:
  name: test-project
plugins: {}
mcp:
  enabled-mcp:
    command: test-command
    scope: project
    enabled: true
  disabled-mcp:
    command: disabled-command
    scope: project
    enabled: false
