import * as path from 'path';
import * as os from 'os';

export const OVERTURE_DIR = '.overture';
export const CONFIG_FILE = 'config.yaml';
export const CONFIG_PATH = path.join(OVERTURE_DIR, CONFIG_FILE);

export const MCP_JSON_FILE = '.mcp.json';
export const CLAUDE_MD_FILE = 'CLAUDE.md';

export const GLOBAL_CONFIG_DIR = path.join(
  os.homedir(),
  '.config',
  'overture'
);

export const DEFAULT_CONFIG_VERSION = '1.0';

export const PROJECT_TYPES = [
  'python-backend',
  'typescript-frontend',
  'node-backend',
  'fullstack',
  'data-science',
  'kubernetes',
] as const;

export const CLAUDE_MD_HEADER = `# CLAUDE.md

<!-- Generated by Overture CLI - Do not edit this section directly -->
<!-- Custom sections below this comment will be preserved -->

`;
